### PR TITLE
[10.0][FIX] connector_carepoint: Use default tz to localize dates

### PR DESCRIPTION
**Pull request by tedsalmon**
* Localize search dates using the backends default timezone
* Add pytz to requirements

Depends:
- [x] #39

### CODE REVIEW

**Comment by tedsalmon** [comment]
@lasley,

What happened to the vertical-medical module `medical_prescription_sale_stock`? All 10.0 builds of `carepoint_connector` are failing because it's not available in `release/10.0` :/

**Comment by lasley** [comment]
It's `sale_stock_medical_prescription` now

**Comment by tedsalmon** [comment]
Hey @lasley,

I've fixed the build issues in #39 - I'll rebase that onto this when it's accepted.

**Comment by lasley** [comment]
You can rebase

**Review by lasley — APPROVED** [review]

**Pull request merged**
