### PR TITLE
[ADD] connector_carepoint: Prescription Export

### PR DESCRIPTION
**Pull request by lasley**
- Add prescription export logic
- Add prescription line export logic
- Switch to delayed import for monograph data
- Disable account export temporarily, will resolve in sales

Depends
- [x] #19

### CODE REVIEW

**Comment by lasley** [comment]
Alright we should be green here. Migration is untested programmatically because it would really just be me testing implementation of two cursor executions.

You should make sure this works as intended though with the migrations. Will need to create a local, install the `release/9.0` branch, switch to this branch, update, verify the following tables no longer exist:
- carepoint_medical_prescription_order_line
- carepoint_carepoint_organization

And these do:
- carepoint_rx_ord_ln
- carepoint_org_bind

The namespace changes were necessary to circumvent OCA/connector#209

**Review by tedsalmon — CHANGES_REQUESTED** [review]
Hey @lasley,

The upgrade added the two tables it should've but it left behind the old tables as well. Please see this screenshot:

screen shot 2016-10-10 at 00 12 16

This was done on my local Odoo 9 dev VM.

Thanks!

**Comment by lasley** [comment]
Alright should hopefully be good this time. Otherwise we scrap it and perform the migration manually :derp:

**Review by tedsalmon — APPROVED** [review]

**Comment by tedsalmon** [comment]
👍 - The changes successfully migrated the tables on upgrade:
screen shot 2016-10-12 at 15 26 52

**Comment by lasley** [comment]
Rebased on current `release/9.0` to fix lint errors & squashed commits. We should be good to merge assuming Travis goes 🍏

**Comment by tedsalmon** [comment]
Thanks @lasley - I was scratching my head as to why these lint errors were there, hence the lack of merge :P

**Comment by lasley** [comment]
Caused by #24 - the guard lints just came out of beta, so are new fails

**Pull request merged**
