### PR TITLE
[9.0][ADD] Create inventory sync component

### PR DESCRIPTION
**Pull request by lasley**
Centralize model attrs  …
- Add default backend
- Move created_at and updated_at to connector
- Remove duplicated attribute definitions
- Remove duplicated sql constraints
- Remove non-functional fdb pem mogc tests

Inventory handling  …
- Restructure medicament and rename to carepoint.item
- Add stock.warehouse & add to medical.pharmacy depends
- Add carepoint vendor

### CODE REVIEW

**Comment by lasley** [comment]
Rebased after #1 merge

This will also be an interesting test of CodeCov integration

**Comment by tedsalmon** [comment]
@lasley -

Couple questions before I merge - Do we care about the endless lint warnings about the way you import?

Also, there's a warning in the tests; not really a problem but:

```
medical.pharmacy.create() includes unknown fields: store_id
```

**Comment by lasley** [comment]
Nah we're going to need to make a pass and clean all of that up at some point but not today and not in this PR.

**Comment by tedsalmon** [comment]
👍

**Pull request merged**
