### PR TITLE
[FIX] connector_carepoint: Use default tz to localize dates

### PR DESCRIPTION
**Pull request by tedsalmon**
* Localize search dates using the backends default timezone
* Add pytz to requirements

### CODE REVIEW

**Comment by lasley** [comment]
This is an incorrect solution.

The correct solution is to provide a TZ dropdown in the backend, similar to the one that already exists for the TZ to default users to. This dropdown should represent the time zone in which the CarePoint server resides.

The [`_import_from_date`](https://github.com/LasLabs/odoo-connector-carepoint/blob/release/10.0/connector_carepoint/models/carepoint_backend.py#L263) method should then do the differential.

Also, pytz is in Odoo core - https://github.com/odoo/odoo/search?utf8=✓&q=pytz

**Comment by tedsalmon** [comment]
@lasley,

What does the timezone under "Localization" represent, if not the timezone the CarePoint server is running in?

screen shot 2017-01-25 at 09 39 47

Thanks!

**Comment by lasley** [comment]
The partners that are all created. So maybe change that to "Partner Localization"?

**Comment by lasley** [comment]
Note - in practice they will probably both be the same time zone. But in configuration, we want the option definitely.

**Comment by tedsalmon** [comment]
@lasley,

Got it; Now it all makes sense. I'll make the necessary changes! (yougotitdude)

**Comment by tedsalmon** [comment]
@lasley,

Changes have been made. Backend looks good:
screen shot 2017-01-25 at 12 40 02

Thanks!

**Comment by lasley** [comment]
@tedsalmon Tests are failing

**Comment by tedsalmon** [comment]
@lasley,

The failing tests are unrelated to my changes:

There's a test in test_medical_patient_disease failing
And:
```
2017-01-25 21:23:24,103 5457 WARNING openerp_test openerp.models: method medical.physician._check_dea_num: @constrains parameter 'country_id' is not writeable
2017-01-25 21:23:24,104 5457 WARNING openerp_test openerp.models: method medical.physician._check_npi_num: @constrains parameter 'country_id' is not writeable
```

**Comment by lasley** [comment]
Test in 9 are irrelevant, LasLabs incubator is partially broken in 9 & OCA doesn't have everything yet.

Please create another PR to the v10 branch with a forward port. We will merge this one optimistically on a green there.

**Review by lasley — APPROVED** [review]
@tedsalmon - please cherry pick in your name changes from the v10 PR & we can merge this

**Pull request merged**
